tab_spaces = 2
fn_params_layout = "Compressed"
max_width = 120
fn_call_width = 120
format_code_in_doc_comments = true
imports_granularity = "Item"
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"